### ISSUE TITLE
期望添加debug依赖

### ISSUE THREAD

**Issue by kongnanlive** [shixinzhang/AndroidBitmapMonitor#1]
大佬参考下[leakcanary](https://square.github.io/leakcanary/getting_started/)，期望开发期间能发现问题并修正，但是正式上线后不希望有代码编译运行到用户真实环境中。

**Comment by HongJianLiu** [comment]
大佬，集成后，超限的大图，显示不出来，展示为黑图，有时间望优化一下
库很有用，感谢

**Comment by shixinzhang** [comment]
> 

收到，我找时间支持一下，当然也期望你可以参与进来，提个 pr 哈哈。

**Comment by shixinzhang** [comment]
@kongnanlive 您反馈的功能已经支持，麻烦升级到 1.0.8 版本，感谢反馈～
implementation 'io.github.shixinzhang:android-bitmap-monitor:1.0.8'

**Comment by shixinzhang** [comment]
@HongJianLiu 您反馈的问题解决了，麻烦升级到 1.0.8 版本，感谢反馈～
implementation 'io.github.shixinzhang:android-bitmap-monitor:1.0.8'

**Comment by shixinzhang** [comment]
@kongnanlive  您反馈的功能已经支持，麻烦升级到 1.0.8 版本，感谢反馈～
    releaseImplementation 'io.github.shixinzhang:android-bitmap-monitor-no-op:1.0.8'
    debugImplementation 'io.github.shixinzhang:android-bitmap-monitor:1.0.8'

**Comment by shixinzhang** [comment]
@kongnanlive 这个功能已经支持了，麻烦升级到最新版本，感谢反馈～

**Comment by shixinzhang** [comment]
@HongJianLiu 这个问题已经修复了，麻烦升级到最新版本，感谢反馈～
