### ISSUE TITLE
你好请教个问题

### ISSUE THREAD

**Issue by yghysdr** [shixinzhang/AndroidBitmapMonitor#11]
_ZN7android6bitmap12createBitmapEP7_JNIEnvPNS_6BitmapEiP11_jbyteArrayP8_jobjecti 你好请教个问题 这个函数符号你是怎么获取的

**Comment by oksep** [comment]
@shixinzhang 大佬，同问

**Comment by oksep** [comment]
@yghysdr 找到了

> adb pull system/lib/libandroid_runtime.so
> arm-linux-androideabi-nm -D libandroid_runtime.so | grep bitmap

参考：https://juejin.cn/post/7084934068416512008
