### ISSUE TITLE
查看图片的时候黑屏

### ISSUE THREAD

**Issue by df13954** [shixinzhang/AndroidBitmapMonitor#2]
接入SDK之后，点击进入图片捕获列表，点击其中的图片进行查看详情。绝大部分图片都是黑的，没有显示出来。

环境：
android 10,pixel3.
implementation "com.github.bumptech.glide:annotations:4.12.0"

![screen_cap_20230222_155504](https://user-images.githubusercontent.com/18607031/220557950-5e70f19a-256b-4d98-b39f-00310080e9ec.png)

**Comment by shixinzhang** [comment]
收到，目前看应该和图片加载框架有关，Picasso 正常，Glide 在有的设备上会还原失败，这个问题我找时间看看，感谢反馈

**Comment by ff-frida** [comment]
> 收到，目前看应该和图片加载框架有关，Picasso 正常，Glide 在有的设备上会还原失败，这个问题我找时间看看，感谢反馈

好的，期待更新

**Comment by uchiaitachipro** [comment]
@shixinzhang 大佬我们项目也用了glide 。经过我不严谨的排查发现是Glide的图片复用逻辑导致的。setInBitmap创建了Bitmap 单这个时候是没有数据的，在decodeFromStream的时候会复用inBitmap的Bitmap。所以hook时机写入的Bitmap 就为黑图了。大佬看看怎么支持下？

**Comment by shixinzhang** [comment]
@ff-frida 这个问题解决了，麻烦升级到 1.0.8 版本，感谢你的反馈～
implementation 'io.github.shixinzhang:android-bitmap-monitor:1.0.8'

**Comment by shixinzhang** [comment]
@uchiaitachipro 这个问题解决了，麻烦升级到 1.0.8 版本，感谢你的反馈～
implementation 'io.github.shixinzhang:android-bitmap-monitor:1.0.8'

**Comment by shixinzhang** [comment]
@uchiaitachipro @ff-frida 这个问题已经修复了，麻烦升级到最新版本，感谢反馈～

**Comment by ff-frida** [comment]
![screen_cap_20230227_165102](https://user-images.githubusercontent.com/18607031/221517434-0ce47f0b-6571-4819-ad48-a667fe709512.png)
![screen_cap_20230227_165229](https://user-images.githubusercontent.com/18607031/221517468-4df96a71-5282-4bce-a618-acd495feecb7.png)
![screen_cap_20230227_165238](https://user-images.githubusercontent.com/18607031/221517498-0f567afa-49b1-4759-87cd-03b548328aa5.png)
更新到109版本，确实可以看到图片了，但是有部分图片看不到，有部分是花屏的。

**Comment by df13954** [comment]
> @df13954 您可以上传一下会花屏的原始文件吗，我来看看原始图片数据，在哪一步还原出了问题。

不好意识，最近忙，来了，我上传个坏图。

github不支持格式，我丢网盘了

链接: https://pan.baidu.com/s/1ogXEk8xSXZZmfNv-2isl3A?pwd=3333 提取码: 3333 复制这段内容后打开百度网盘手机App，操作更方便哦 
--来自百度网盘超级会员v2的分享

**Comment by shixinzhang** [comment]
@df13954 收到，最近同样事情比较多😭，周末找时间看下
