### ISSUE TITLE
每次启动都会将超出阈值的图片写入不同的文件，可能造成存储耗尽

### ISSUE THREAD

**Issue by RicardoJiang** [shixinzhang/AndroidBitmapMonitor#6]
每次启动都会将超出阈值的图片写入不同的文件，多打开几次后，bitmap_monitor 目录下的文件越来越多，可能造成存储耗尽

**Comment by yibaoshan** [comment]
收到~ 

文件上限管理已经开发完成，在内测阶段，稍候会发布新版本重复保存图片的问题正在解决，感谢反馈~

**Comment by yibaoshan** [comment]
> 每次启动都会将超出阈值的图片写入不同的文件，多打开几次后，bitmap_monitor 目录下的文件越来越多，可能造成存储耗尽

收到 (*╹▽╹*) 感谢您的反馈~

文件上限管理目前已经开发完成，在内测阶段，稍候会发布新版本；重复保存图片的问题也正在解决，预计会在下下个版本中发布，再次感谢反馈~

**Comment by shixinzhang** [comment]
@RicardoJiang 您好，您反馈的问题我们已经解决，麻烦升级到 1.1.0 版本，感谢反馈！
